#include "application_templates.h"

const char *template_application_cmakelists =
"cmake_minimum_required(VERSION 3.17)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Project\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"project(\n"
"    @PACKAGE_NAME@\n"
"    VERSION 1.0.0\n"
"    LANGUAGES C\n"
")\n"
"\n"
"set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n"
"\n"
"option(@PACKAGE_UPPER@_BUILD_TESTS \"Build @PACKAGE_UPPER@ tests\" OFF)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Dependencies\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"find_package(Harp REQUIRED)\n"
"\n"
"# Packages are placed in packages/ relative to the build output.\n"
"# Add package subdirectories below and they will deploy themselves.\n"
"set(HARP_PACKAGES_DIR \"${CMAKE_BINARY_DIR}/packages\")\n"
"\n"
"# add_subdirectory(path/to/package)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Executable\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"add_executable(@PACKAGE_NAME@ src/main.c)\n"
"\n"
"target_compile_features(@PACKAGE_NAME@ PRIVATE c_std_23)\n"
"\n"
"target_link_libraries(@PACKAGE_NAME@ PRIVATE HARP::Harp)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Tests\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"if(@PACKAGE_UPPER@_BUILD_TESTS)\n"
"    enable_testing()\n"
"    add_subdirectory(tests)\n"
"endif()\n";

const char *template_application_main_c =
"#include <harp/harp_core.h>\n"
"\n"
"#include <stdint.h>\n"
"\n"
"int main(int argc, char **argv) {\n"
"    (void)argc;\n"
"\n"
"    HarpRuntimeCreator creator = { .argv0 = argv[0] };\n"
"    HarpRuntime *runtime = NULL;\n"
"\n"
"    if(harp_initialize((const HarpCreatorBase *)&creator, &runtime) != HARP_RESULT_OK)\n"
"        return 1;\n"
"\n"
"    if(harp_runtime_load_packages(runtime) != HARP_RESULT_OK) {\n"
"        harp_terminate(runtime);\n"
"        return 1;\n"
"    }\n"
"\n"
"    HarpDependencyDesc core_dep = {\n"
"        .name        = HARP_CORE_HANDLER_NAME,\n"
"        .min_version = 0,\n"
"        .max_version = UINT32_MAX\n"
"    };\n"
"    HarpHandlerBase *core_base = NULL;\n"
"\n"
"    if(harp_runtime_get_handler(runtime, &core_dep, &core_base) != HARP_RESULT_OK) {\n"
"        harp_terminate(runtime);\n"
"        return 1;\n"
"    }\n"
"\n"
"    HarpCoreHandler *core = (HarpCoreHandler *)core_base;\n"
"    (void)core;\n"
"\n"
"    harp_terminate(runtime);\n"
"    return 0;\n"
"}\n";

const char *template_application_tests_cmakelists =
"# add_executable(test_example test_example.c)\n"
"# target_link_libraries(test_example PRIVATE HARP::Harp)\n"
"# add_test(NAME test_example COMMAND test_example)\n";