#include "application_templates.h"

const char *template_application_cmakelists =
"cmake_minimum_required(VERSION 3.17)\n"
"\n"
"project(@PACKAGE_UPPER@ LANGUAGES C)\n"
"\n"
"find_package(Harp REQUIRED)\n"
"\n"
"add_executable(@PACKAGE_NAME@)\n"
"\n"
"target_sources(\n"
"    @PACKAGE_NAME@ PRIVATE\n"
"    src/main.c\n"
")\n"
"\n"
"target_link_libraries(\n"
"    @PACKAGE_NAME@ PRIVATE\n"
"    HARP::Harp\n"
")\n";

const char *template_application_main_c =
"#include <harp/harp_core.h>\n"
"\n"
"int main(\n"
"    int argc,\n"
"    char **argv\n"
") {\n"
"    HarpRuntimeCreator creator = {\n"
"        .argv0 = argv[0]\n"
"    };\n"
"\n"
"    HarpRuntime *runtime = NULL;\n"
"\n"
"    if(harp_initialize(\n"
"        (const HarpCreatorBase *)&creator,\n"
"        &runtime\n"
"    ) != HARP_RESULT_OK)\n"
"        return 1;\n"
"\n"
"    harp_runtime_load_packages(runtime);\n"
"\n"
"    harp_terminate(runtime);\n"
"    return 0;\n"
"}\n";