#include "package_templates.h"

const char *template_package_cmakelists =
"cmake_minimum_required(VERSION 3.17)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Project\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"project(\n"
"    @PACKAGE_NAME@\n"
"    VERSION 1.0.0\n"
"    LANGUAGES C\n"
")\n"
"\n"
"set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n"
"\n"
"option(@PACKAGE_UPPER@_BUILD_TESTS \"Build @PACKAGE_UPPER@ tests\" OFF)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Dependencies\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"find_package(Harp REQUIRED)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Interface\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"add_library(@PACKAGE_NAME@Interface INTERFACE)\n"
"add_library(@PACKAGE_UPPER@::Interface ALIAS @PACKAGE_NAME@Interface)\n"
"\n"
"set_target_properties(@PACKAGE_NAME@Interface PROPERTIES\n"
"    EXPORT_NAME Interface\n"
")\n"
"\n"
"target_include_directories(\n"
"    @PACKAGE_NAME@Interface INTERFACE\n"
"    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>\n"
"    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>\n"
")\n"
"\n"
"target_link_libraries(@PACKAGE_NAME@Interface INTERFACE HARP::Interface)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Shared Library\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"add_library(@PACKAGE_NAME@ SHARED)\n"
"add_library(@PACKAGE_UPPER@::@PACKAGE_NAME@ ALIAS @PACKAGE_NAME@)\n"
"\n"
"target_sources(\n"
"    @PACKAGE_NAME@ PRIVATE\n"
"    src/@PREFIX_LOWER@_package.c\n"
"    src/impl/@PREFIX_LOWER@_hello_handler.c\n"
")\n"
"\n"
"target_compile_features(@PACKAGE_NAME@ PUBLIC c_std_23)\n"
"\n"
"target_link_libraries(@PACKAGE_NAME@ PUBLIC @PACKAGE_NAME@Interface)\n"
"\n"
"target_include_directories(@PACKAGE_NAME@ PRIVATE src)\n"
"\n"
"harp_package(TARGET @PACKAGE_NAME@ SUBDIRECTORY)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Tests\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"if(@PACKAGE_UPPER@_BUILD_TESTS)\n"
"    add_subdirectory(tests)\n"
"endif()\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Installation\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"include(GNUInstallDirs)\n"
"\n"
"install(\n"
"    DIRECTORY include/\n"
"    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}\n"
")\n"
"\n"
"install(\n"
"    TARGETS @PACKAGE_NAME@Interface\n"
"    EXPORT @PACKAGE_NAME@Targets\n"
"    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}\n"
")\n"
"\n"
"install(\n"
"    EXPORT @PACKAGE_NAME@Targets\n"
"    FILE @PACKAGE_NAME@Targets.cmake\n"
"    NAMESPACE @PACKAGE_UPPER@::\n"
"    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/@PACKAGE_NAME@\n"
")\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Package Configuration\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"include(CMakePackageConfigHelpers)\n"
"\n"
"write_basic_package_version_file(\n"
"    \"${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@ConfigVersion.cmake\"\n"
"    VERSION ${PROJECT_VERSION}\n"
"    COMPATIBILITY SameMajorVersion\n"
")\n"
"\n"
"configure_package_config_file(\n"
"    cmake/PackageConfig.cmake.in\n"
"    ${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@Config.cmake\n"
"    INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/@PACKAGE_NAME@\n"
")\n"
"\n"
"install(\n"
"    FILES\n"
"        ${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@Config.cmake\n"
"        ${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@ConfigVersion.cmake\n"
"    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/@PACKAGE_NAME@\n"
")\n";


const char *template_package_config =
"@PACKAGE_INIT@\n"
"\n"
"include(\"${CMAKE_CURRENT_LIST_DIR}/@PACKAGE_NAME@Targets.cmake\")\n";


const char *template_package_h =
"#ifndef @PREFIX_UPPER@_H\n"
"#define @PREFIX_UPPER@_H\n"
"\n"
"#ifdef __cplusplus\n"
"extern \"C\" {\n"
"#endif\n"
"\n"
"#include <harp/harp.h>\n"
"#include <harp/utils/harp_version.h>\n"
"\n"
"\n"
"#define @PREFIX_UPPER@_PACKAGE_NAME   \"@PACKAGE_NAME@\"\n"
"#define @PREFIX_UPPER@_PACKAGE_VERSION HARP_MAKE_VERSION(1,0,0)\n"
"\n"
"#define @PREFIX_UPPER@_HELLO_HANDLER_NAME    \"@PREFIX_LOWER@HelloHandler\"\n"
"#define @PREFIX_UPPER@_HELLO_HANDLER_VERSION  HARP_MAKE_VERSION(1,0,0)\n"
"\n"
"typedef struct @PREFIX_LOWER@HelloHandler {\n"
"    HarpHandlerBase _base;\n"
"\n"
"    void (*hello)(struct @PREFIX_LOWER@HelloHandler *handler);\n"
"} @PREFIX_LOWER@HelloHandler;\n"
"\n"
"\n"
"#ifdef __cplusplus\n"
"}\n"
"#endif\n"
"\n"
"#endif\n";


const char *template_package_impl_api_h =
"#ifndef @PREFIX_UPPER@_HELLO_HANDLER_IMPL_H\n"
"#define @PREFIX_UPPER@_HELLO_HANDLER_IMPL_H\n"
"\n"
"#include <@PACKAGE_LOWER@/@PREFIX_LOWER@.h>\n"
"\n"
"HarpResult @PREFIX_LOWER@_hello_handler_init(\n"
"    HarpCoreHandler *core,\n"
"    HarpHandlerBase *handler,\n"
"    HarpCreatorBase *creator\n"
");\n"
"\n"
"HarpResult @PREFIX_LOWER@_hello_handler_term(\n"
"    HarpCoreHandler *core,\n"
"    HarpHandlerBase *handler\n"
");\n"
"\n"
"void @PREFIX_LOWER@_hello(\n"
"    @PREFIX_LOWER@HelloHandler *handler\n"
");\n"
"\n"
"#endif\n";


const char *template_package_impl_api_c =
"#include \"@PREFIX_LOWER@_hello_handler.h\"\n"
"\n"
"#include <stdio.h>\n"
"\n"
"HarpResult @PREFIX_LOWER@_hello_handler_init(\n"
"    HarpCoreHandler *core,\n"
"    HarpHandlerBase *handler,\n"
"    HarpCreatorBase *creator\n"
") {\n"
"    (void)core;\n"
"    (void)creator;\n"
"\n"
"    @PREFIX_LOWER@HelloHandler *h = (@PREFIX_LOWER@HelloHandler *)handler;\n"
"    h->hello = @PREFIX_LOWER@_hello;\n"
"\n"
"    return HARP_RESULT_OK;\n"
"}\n"
"\n"
"HarpResult @PREFIX_LOWER@_hello_handler_term(\n"
"    HarpCoreHandler *core,\n"
"    HarpHandlerBase *handler\n"
") {\n"
"    (void)core;\n"
"    (void)handler;\n"
"\n"
"    return HARP_RESULT_OK;\n"
"}\n"
"\n"
"void @PREFIX_LOWER@_hello(\n"
"    @PREFIX_LOWER@HelloHandler *handler\n"
") {\n"
"    (void)handler;\n"
"\n"
"    printf(\"Hello from @PACKAGE_NAME@!\\n\");\n"
"}\n";


const char *template_package_c =
"#include <@PACKAGE_LOWER@/@PREFIX_LOWER@.h>\n"
"#include \"impl/@PREFIX_LOWER@_hello_handler.h\"\n"
"\n"
"#include <harp/harp.h>\n"
"\n"
"#include <stdalign.h>\n"
"\n"
"HarpResult @PREFIX_LOWER@_register(\n"
"    HarpCoreHandler *core\n"
") {\n"
"    static HarpHandlerDesc desc = {\n"
"        .name             = @PREFIX_UPPER@_HELLO_HANDLER_NAME,\n"
"        .version          = @PREFIX_UPPER@_HELLO_HANDLER_VERSION,\n"
"        .instance_size    = sizeof(@PREFIX_LOWER@HelloHandler),\n"
"        .instance_alignment = alignof(@PREFIX_LOWER@HelloHandler),\n"
"\n"
"        .pfn_init = @PREFIX_LOWER@_hello_handler_init,\n"
"        .pfn_term = @PREFIX_LOWER@_hello_handler_term,\n"
"\n"
"        .p_dependencies   = NULL,\n"
"        .dependency_count = 0\n"
"    };\n"
"\n"
"    return core->register_handler(core, &desc);\n"
"}\n"
"\n"
"HarpResult harp_package_query(\n"
"    HarpPackageDesc **out_desc\n"
") {\n"
"    static HarpPackageDesc package_desc = {\n"
"        .name    = @PREFIX_UPPER@_PACKAGE_NAME,\n"
"        .version = @PREFIX_UPPER@_PACKAGE_VERSION,\n"
"\n"
"        .pfn_register     = @PREFIX_LOWER@_register,\n"
"\n"
"        .p_dependencies   = NULL,\n"
"        .dependency_count = 0\n"
"    };\n"
"\n"
"    if(out_desc == NULL)\n"
"        return HARP_RESULT_MISSING_OUTPUT;\n"
"\n"
"    *out_desc = &package_desc;\n"
"\n"
"    return HARP_RESULT_OK;\n"
"}\n";


const char *template_gitignore =
".vscode/\n"
".idea/\n"
".cache/\n"
"build/\n"
"\n"
"*~\n"
"*.swp\n"
"*.swo\n"
"\n"
"compile_commands.json\n";


const char *template_tests_cmakelists =
"add_executable(\n"
"    test_@PACKAGE_LOWER@_hello\n"
"    test_hello.c\n"
")\n"
"\n"
"target_link_libraries(\n"
"    test_@PACKAGE_LOWER@_hello PRIVATE\n"
"    @PACKAGE_NAME@\n"
")\n"
"\n"
"target_include_directories(\n"
"    test_@PACKAGE_LOWER@_hello PRIVATE\n"
"    ${CMAKE_CURRENT_SOURCE_DIR}/../src\n"
")\n"
"\n"
"add_test(\n"
"    NAME test_@PACKAGE_LOWER@_hello\n"
"    COMMAND test_@PACKAGE_LOWER@_hello\n"
")\n";


const char *template_tests_hello =
"#include <assert.h>\n"
"#include <stdio.h>\n"
"\n"
"#include <harp/harp_core.h>\n"
"#include <@PACKAGE_LOWER@/@PREFIX_LOWER@.h>\n"
"\n"
"int main(int argc, char **argv) {\n"
"    HarpRuntimeCreator creator = { .argv0 = argv[0] };\n"
"    HarpRuntime *runtime = NULL;\n"
"\n"
"    assert(harp_initialize((const HarpCreatorBase *)&creator, &runtime) == HARP_RESULT_OK);\n"
"\n"
"    assert(harp_runtime_load_packages(runtime) == HARP_RESULT_OK);\n"
"\n"
"    HarpDependencyDesc core_dep = {\n"
"        .name = HARP_CORE_HANDLER_NAME,\n"
"        .min_version = 0,\n"
"        .max_version = UINT32_MAX\n"
"    };\n"
"    HarpHandlerBase *core_base = NULL;\n"
"    assert(harp_runtime_get_handler(runtime, &core_dep, &core_base) == HARP_RESULT_OK);\n"
"    HarpCoreHandler *core = (HarpCoreHandler *)core_base;\n"
"\n"
"    HarpCreatorBase empty_creator = {0};\n"
"    assert(core->handler_initialize(core, @PREFIX_UPPER@_HELLO_HANDLER_NAME, &empty_creator) == HARP_RESULT_OK);\n"
"\n"
"    HarpDependencyDesc dep = {\n"
"        .name = @PREFIX_UPPER@_HELLO_HANDLER_NAME,\n"
"        .min_version = 0,\n"
"        .max_version = UINT32_MAX\n"
"    };\n"
"    HarpHandlerBase *handler_base = NULL;\n"
"    assert(harp_runtime_get_handler(runtime, &dep, &handler_base) == HARP_RESULT_OK);\n"
"    @PREFIX_LOWER@HelloHandler *hello = (@PREFIX_LOWER@HelloHandler *)handler_base;\n"
"\n"
"    hello->hello(hello);\n"
"\n"
"    assert(harp_terminate(runtime) == HARP_RESULT_OK);\n"
"\n"
"    printf(\"Test passed\\n\");\n"
"    return 0;\n"
"}\n";