#include "package_templates.h"

const char *template_package_cmakelists =
"cmake_minimum_required(VERSION 3.17)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Project\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"project(\n"
"    @PACKAGE_UPPER@\n"
"    VERSION 1.0.0\n"
"    LANGUAGES C\n"
")\n"
"\n"
"set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n"
"\n"
"option(@PACKAGE_UPPER@_BUILD_TESTS \"Build @PACKAGE_UPPER@ tests\" OFF)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Dependencies\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"find_package(Harp REQUIRED)\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Interface\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"add_library(@PACKAGE_NAME@Interface INTERFACE)\n"
"add_library(@PACKAGE_UPPER@::Interface ALIAS @PACKAGE_NAME@Interface)\n"
"\n"
"set_target_properties(\n"
"    @PACKAGE_NAME@Interface PROPERTIES\n"
"    EXPORT_NAME Interface\n"
")\n"
"\n"
"target_include_directories(\n"
"    @PACKAGE_NAME@Interface INTERFACE\n"
"    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>\n"
"    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>\n"
")\n"
"\n"
"target_link_libraries(\n"
"    @PACKAGE_NAME@Interface INTERFACE\n"
"    HARP::Interface\n"
")\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Shared Library\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"add_library(@PACKAGE_NAME@ SHARED)\n"
"add_library(@PACKAGE_UPPER@::@PACKAGE_NAME@ ALIAS @PACKAGE_NAME@)\n"
"\n"
"set_target_properties(\n"
"    @PACKAGE_NAME@ PROPERTIES\n"
"    EXPORT_NAME @PACKAGE_NAME@\n"
"    PREFIX \"\"\n"
")\n"
"\n"
"target_sources(\n"
"    @PACKAGE_NAME@ PRIVATE\n"
"    src/@PREFIX_LOWER@_package.c\n"
"    src/impl/@PREFIX_LOWER@_hello_api.c\n"
")\n"
"\n"
"target_compile_features(\n"
"    @PACKAGE_NAME@ PUBLIC\n"
"    c_std_23\n"
")\n"
"\n"
"target_link_libraries(\n"
"    @PACKAGE_NAME@ PUBLIC\n"
"    @PACKAGE_NAME@Interface\n"
")\n"
"\n"
"target_include_directories(\n"
"    @PACKAGE_NAME@\n"
"    PRIVATE\n"
"        src\n"
"    PUBLIC\n"
"        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>\n"
"        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>\n"
")\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Tests\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"if(@PACKAGE_UPPER@_BUILD_TESTS)\n"
"    add_subdirectory(tests)\n"
"endif()\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Installation\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"include(GNUInstallDirs)\n"
"\n"
"install(\n"
"    DIRECTORY include/\n"
"    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}\n"
")\n"
"\n"
"install(\n"
"    TARGETS\n"
"        @PACKAGE_NAME@Interface\n"
"        @PACKAGE_NAME@\n"
"\n"
"    EXPORT @PACKAGE_NAME@Targets\n"
"\n"
"    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}\n"
"\n"
"    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}\n"
"    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}\n"
"    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}\n"
")\n"
"\n"
"install(\n"
"    EXPORT @PACKAGE_NAME@Targets\n"
"    FILE @PACKAGE_NAME@Targets.cmake\n"
"    NAMESPACE @PACKAGE_UPPER@::\n"
"    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/@PACKAGE_NAME@\n"
")\n"
"\n"
"# ------------------------------------------------------------------------------\n"
"# Package Configuration\n"
"# ------------------------------------------------------------------------------\n"
"\n"
"include(CMakePackageConfigHelpers)\n"
"\n"
"write_basic_package_version_file(\n"
"    \"${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@ConfigVersion.cmake\"\n"
"    VERSION ${PROJECT_VERSION}\n"
"    COMPATIBILITY SameMajorVersion\n"
")\n"
"\n"
"configure_package_config_file(\n"
"    cmake/PackageConfig.cmake.in\n"
"    ${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@Config.cmake\n"
"    INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/@PACKAGE_NAME@\n"
")\n"
"\n"
"install(\n"
"    FILES\n"
"        ${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@Config.cmake\n"
"        ${CMAKE_CURRENT_BINARY_DIR}/@PACKAGE_NAME@ConfigVersion.cmake\n"
"    DESTINATION\n"
"        ${CMAKE_INSTALL_LIBDIR}/cmake/@PACKAGE_NAME@\n"
")\n";


const char *template_package_config =
"@PACKAGE_INIT@\n"
"\n"
"include(\"${CMAKE_CURRENT_LIST_DIR}/@PACKAGE_NAME@Targets.cmake\")\n";


const char *template_package_h =
"#ifndef @PREFIX_UPPER@_H\n"
"#define @PREFIX_UPPER@_H\n"
"\n"
"#ifdef __cplusplus\n"
"extern \"C\" {\n"
"#endif\n"
"\n"
"#include <harp/harp.h>\n"
"\n"
"#undef HARP_UTILS_UNDEF\n"
"#include <harp/utils/harp_api.h>\n"
"#include <harp/utils/harp_version.h>\n"
"\n"
"\n"
"#define @PREFIX_UPPER@_PACKAGE_NAME \"@PACKAGE_NAME@\"\n"
"#define @PREFIX_UPPER@_PACKAGE_VERSION HARP_MAKE_VERSION(1,0,0)\n"
"\n"
"#define @PREFIX_UPPER@_HELLO_API_NAME \"@PREFIX_LOWER@HelloApi\"\n"
"#define @PREFIX_UPPER@_HELLO_API_VERSION HARP_MAKE_VERSION(1,0,0)\n"
"\n"
"typedef struct @PREFIX_LOWER@HelloApi {\n"
"    HarpApiBase _base;\n"
"\n"
"    void (*hello)(struct @PREFIX_LOWER@HelloApi *api);\n"
"} @PREFIX_LOWER@HelloApi;\n"
"\n"
"\n"
"#define HARP_UTILS_UNDEF\n"
"#include <harp/utils/harp_api.h>\n"
"#undef HARP_UTILS_UNDEF\n"
"\n"
"#ifdef __cplusplus\n"
"}\n"
"#endif\n"
"\n"
"#endif\n";


const char *template_package_impl_api_h =
"#ifndef @PREFIX_UPPER@_HELLO_API_IMPL_H\n"
"#define @PREFIX_UPPER@_HELLO_API_IMPL_H\n"
"\n"
"#include <@PACKAGE_LOWER@/@PREFIX_LOWER@.h>\n"
"\n"
"void @PREFIX_LOWER@_api_hello(\n"
"    @PREFIX_LOWER@HelloApi *api\n"
");\n"
"\n"
"#endif\n";


const char *template_package_impl_api_c =
"#include \"@PREFIX_LOWER@_hello_api.h\"\n"
"\n"
"#include <stdio.h>\n"
"\n"
"void @PREFIX_LOWER@_api_hello(\n"
"    @PREFIX_LOWER@HelloApi *api\n"
") {\n"
"    (void)api;\n"
"\n"
"    printf(\"Hello from @PACKAGE_NAME@!\\n\");\n"
"}\n";


const char *template_package_c =
"#include <@PACKAGE_LOWER@/@PREFIX_LOWER@.h>\n"
"#include \"impl/@PREFIX_LOWER@_hello_api.h\"\n"
"\n"
"#include <harp/harp.h>\n"
"#include <harp/utils/harp_api.h>\n"
"\n"
"#include <stdalign.h>\n"
"\n"
"HarpResult @PREFIX_LOWER@_register(\n"
"    HarpCoreApi *core\n"
") {\n"
"    HarpApiDesc desc = {\n"
"        .name = @PREFIX_UPPER@_HELLO_API_NAME,\n"
"        .version = @PREFIX_UPPER@_HELLO_API_VERSION,\n"
"        .instance_size = sizeof(@PREFIX_LOWER@HelloApi),\n"
"        .instance_alignment = alignof(@PREFIX_LOWER@HelloApi)\n"
"    };\n"
"\n"
"    HarpApiBase *base = NULL;\n"
"\n"
"    HarpResult result = HARP_API_CALL(\n"
"        core, register_api,\n"
"        &&desc, &base);\n"
"    if(result != HARP_RESULT_OK)\n"
"        return result;\n"
"\n"
"    @PREFIX_LOWER@HelloApi *hello = HARP_API_AS(@PREFIX_LOWER@HelloApi, base);\n"
"\n"
"    hello->hello = @PREFIX_LOWER@_api_hello;\n"
"\n"
"    base->available = 1;\n"
"\n"
"    return HARP_RESULT_OK;\n"
"}\n"
"\n"
"HarpResult harp_package_query(\n"
"    HarpPackageDesc **out_desc\n"
") {\n"
"    static HarpPackageDesc package_desc = {\n"
"        .name = @PREFIX_UPPER@_PACKAGE_NAME,\n"
"        .version = @PREFIX_UPPER@_PACKAGE_VERSION,\n"
"\n"
"        .pfn_register = @PREFIX_LOWER@_register,\n"
"\n"
"        .p_dependencies = NULL,\n"
"        .dependency_count = 0\n"
"    };\n"
"\n"
"    if(out_desc == NULL)\n"
"        return HARP_RESULT_MISSING_OUTPUT;\n"
"\n"
"    *out_desc = &package_desc;\n"
"\n"
"    return HARP_RESULT_OK;\n"
"}\n";


const char *template_gitignore =
".vscode/\n"
".idea/\n"
".cache/\n"
"build/\n"
"\n"
"*~\n"
"*.swp\n"
"*.swo\n"
"\n"
"compile_commands.json\n";


const char *template_tests_cmakelists =
"add_executable(\n"
"    test_@PACKAGE_LOWER@_hello\n"
"    test_hello.c\n"
")\n"
"\n"
"target_link_libraries(\n"
"    test_@PACKAGE_LOWER@_hello PRIVATE\n"
"    @PACKAGE_NAME@\n"
")\n"
"\n"
"target_include_directories(\n"
"    test_@PACKAGE_LOWER@_hello PRIVATE\n"
"    ${CMAKE_CURRENT_SOURCE_DIR}/../src\n"
")\n"
"\n"
"add_test(\n"
"    NAME test_@PACKAGE_LOWER@_hello\n"
"    COMMAND test_@PACKAGE_LOWER@_hello\n"
")\n";


const char *template_tests_hello =
"#include <assert.h>\n"
"#include <stdio.h>\n"
"\n"
"#include \"impl/@PREFIX_LOWER@_hello_api.h\"\n"
"\n"
"int main(void) {\n"
"    @PREFIX_LOWER@HelloApi api = {0};\n"
"\n"
"    @PREFIX_LOWER@_api_hello(&api);\n"
"\n"
"    printf(\"Test passed\\n\");\n"
"    return 0;\n"
"}\n";